main : me.angelfire.angelplus.Main
name: AngelPlus
version: 1.0
author: AngelFire
api-version: 1.16

commands:
  Bonjour:
  Gonflenuage:
  Choose:
  ClanInfo:
  Givechooseperm:
  Pluie:
  Supertnt:
  Creeper: